#!/bin/bash

# > VARIABLES
declare -a options=("Externe" "Interne" "Root")
# < VARIABLES

# Fonction affichant l'OS utilisé
get_os_name() {
    FILE=/etc/os-release
    if test -f "$FILE"; then
        awk -F= '$1=="ID" { print " "$2 ;}' "$FILE"
    fi
}
function_code_os_name=$(declare -f get_os_name)

# Fonction affichant la branche git courante
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1) /'
}
function_code_parse_git_branch=$(declare -f parse_git_branch)

bashFile=$'\n\n'"### PERSONNAL CONFIGURATION"
bashFile+=$'\n'"# OS Distribution name"
bashFileps1+=$'\n'"$function_code_os_name"
bashFile+=$'\n'
bashFile+=$'\n'"# git branch"
bashFile+=$'\n'"$function_code_parse_git_branch"
bashFile+=$'\n'


# Demande du profil
PS3="Veuillez sélectionner un profil (externe, interne, root) : "
select profile in "${options[@]}"; do
	case $profile in
		"Externe")
			profilePS1='\[\e[38;5;33;3m\]\u\[\e[0m\]\[\e[97;1m\]@\[\e[0m\]\[\e[38;5;34m\]\H\[\e[0m\]'
			profileICO='💨'
			break
			;;
		"Interne")
			profilePS1='\[\e[38;5;178m\]\u\[\e[0m\]\[\e[97;1m\]@\[\e[0m\]\[\e[38;5;34m\]\H\[\e[0m\]'
			profileICO='💢'
			break
			;;
		"Root")
			profilePS1='\[\e[38;5;160;1;5m\]\u\[\e[0m\]\[\e[97;1m\]@\[\e[0m\]\[\e[38;5;34m\]\H\[\e[0m\]'
			profileICO='💥'
			break
			;;
		*)
			echo "Option invalide. Veuillez sélectionner un profil valide."
			;;
	esac
done

# Demande d'intégrer le nom de l'OS
while true; do
	read -e -p "Intégrer le nom de l'OS (oui/non) ? " -i "y" yn
	case $yn in
		[Yy]* ) 
			include_os=true
			break
		;;
		[Nn]* ) 
			include_os=false
			break
		;;
		* ) echo "Please answer yes or no.";;
	esac
done

# Demande d'intégrer la branche git courante
while true; do
	read -e -p "Intégrer la branche git courante (oui/non) ? " -i "y" yn
	case $yn in
		[Yy]* ) 
			include_git_branch=true
			break
		;;
		[Nn]* ) 
			include_git_branch=false
			break
		;;
		* ) echo "Please answer yes or no.";;
	esac
done

# Construction du PS1
ps1+="\[\e[38;5;251;1m\]\A\[\e[0m\]" # Heure

# OS
if [ "$include_os" = "oui" ]; then
    ps1+=" \[\e[38;5;230;2m\]$(get_os_name)\[\e[0m\]" # OS utilisé
fi

ps1+=" $profilePS1"

ps1+=" \[\e[0;38;5;184m\]\w\[\e[0m\]" # Path

# git branch
if [ "$include_git_branch" = "oui" ]; then
    ps1+=" \[\e[0;3;38;5;45m\]$(parse_git_branch)\[\e[0m\]" # Branche git
fi

ps1+=$'\n'"$profileICO "

# Integration du PS1 dans le variable fichier
bashFile+=$'\n'"# PROFILE for $USER ($profile)"$'\n'

bashFile+="PS1='$ps1'"$'\n'

echo "$bashFile" > bash.test